./haku examples/adjectives.haku
./haku examples/foldl.haku
./haku examples/haku-raku.haku
./haku examples/iroha.haku
./haku examples/maps.haku
./haku examples/mugendai.haku
./haku examples/pwc131-t1.haku
./haku examples/recursion_let.haku
./haku examples/recursive_length_calc.haku
./haku examples/yuki.haku
./haku examples/zoi_chinamini.haku
./haku examples/dailymaths-25.haku
./haku examples/sum-of-list.haku
